//! A faithful port of ocgcore (edo9300/ygopro-core) to Rust.
//!
//! AGPL-3.0-or-later; see `LICENSE` and `NOTICE`.

pub mod add_chain;
pub mod adjust;
pub mod battle;
pub mod battle_command;
pub mod board;
pub mod capability;
pub mod card;
pub mod card_effects;
pub mod cards;
pub mod chain;
pub mod change_position;
pub mod command_predicates;
pub mod counters;
pub mod damage_step;
pub mod destroy;
pub mod determinize;
pub mod disable;
pub mod discard;
pub mod draw;
pub mod driver;
pub mod duel;
pub mod effect;
pub mod equip;
pub mod event;
pub mod execute;
pub mod field;
pub mod flip_summon;
pub mod fxhash;
pub mod game;
pub mod get_control;
pub mod host_question;
pub mod idle_command;
pub mod leave_field;
pub mod leave_snapshot;
pub mod life_points;
pub mod matching;
pub mod monster_set;
pub mod move_to_field;
pub mod movement;
pub mod observation;
pub mod phase_event;
pub mod point_event;
pub mod processor;
pub mod quick_effect;
pub mod refresh_loc;
pub mod remove_counter;
pub mod replace;
pub mod rng;
pub mod rollout;
pub mod script_api;
pub mod select_release;
pub mod select_tribute;
pub mod self_destroy;
pub mod send_to;
pub mod solve_chain;
pub mod solve_continuous;
pub mod spell_set;
pub mod spell_set_group;
pub mod spsummon;
pub mod spsummon_permission;
pub mod spsummon_rule;
pub mod stats;
pub mod summon_rule;
pub mod summon_support;
pub mod swap_control;
pub mod toss;
pub mod trace;
pub mod trap_monster_adjust;
pub mod tribute;
pub mod turn;

pub use board::{location, position, Loc, PlayerZones};
pub use card::{attribute, card_type, race, reason, status, Card, CardData, CardState};
pub use chain::{chain_flag, Chain, ChainArray, ChainList};
pub use duel::{modes, REFERENCE_CONFIGURATION};
pub use effect::{effect_count, effect_type, flag, flag2, Ctx, Effect, Effects};
pub use event::{code, CardId, EffectId, Event, PLAYER_NONE};
pub use field::{Core, EffectIndex, EventList, Field, FieldEffects, Infos};
pub use processor::{Kind, Status, Unit, RESTART};
